/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CompaniesRouteImport } from './routes/companies'
import { Route as ContactsRouteImport } from './routes/contacts'
import { Route as PipelineRouteImport } from './routes/pipeline'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as CompaniesIndexRouteImport } from './routes/companies.index'
import { Route as CompaniesContactIdRouteImport } from './routes/companies.$contactId'
import { Route as CompaniesOrgCompanyIdRouteImport } from './routes/companies.org.$companyId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesRoute = CompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsRoute = ContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelineRoute = PipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesIndexRoute = CompaniesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CompaniesRoute,
} as any)
const CompaniesContactIdRoute = CompaniesContactIdRouteImport.update({
  id: '/$contactId',
  path: '/$contactId',
  getParentRoute: () => CompaniesRoute,
} as any)
const CompaniesOrgCompanyIdRoute = CompaniesOrgCompanyIdRouteImport.update({
  id: '/org/$companyId',
  path: '/org/$companyId',
  getParentRoute: () => CompaniesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/companies': typeof CompaniesRouteWithChildren
  '/contacts': typeof ContactsRoute
  '/pipeline': typeof PipelineRoute
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRoute
  '/companies/$contactId': typeof CompaniesContactIdRoute
  '/companies/': typeof CompaniesIndexRoute
  '/companies/org/$companyId': typeof CompaniesOrgCompanyIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contacts': typeof ContactsRoute
  '/pipeline': typeof PipelineRoute
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRoute
  '/companies/$contactId': typeof CompaniesContactIdRoute
  '/companies': typeof CompaniesIndexRoute
  '/companies/org/$companyId': typeof CompaniesOrgCompanyIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/companies': typeof CompaniesRouteWithChildren
  '/contacts': typeof ContactsRoute
  '/pipeline': typeof PipelineRoute
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRoute
  '/companies/$contactId': typeof CompaniesContactIdRoute
  '/companies/': typeof CompaniesIndexRoute
  '/companies/org/$companyId': typeof CompaniesOrgCompanyIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/companies'
    | '/contacts'
    | '/pipeline'
    | '/settings'
    | '/tasks'
    | '/companies/$contactId'
    | '/companies/'
    | '/companies/org/$companyId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contacts'
    | '/pipeline'
    | '/settings'
    | '/tasks'
    | '/companies/$contactId'
    | '/companies'
    | '/companies/org/$companyId'
  id:
    | '__root__'
    | '/'
    | '/companies'
    | '/contacts'
    | '/pipeline'
    | '/settings'
    | '/tasks'
    | '/companies/$contactId'
    | '/companies/'
    | '/companies/org/$companyId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompaniesRoute: typeof CompaniesRouteWithChildren
  ContactsRoute: typeof ContactsRoute
  PipelineRoute: typeof PipelineRoute
  SettingsRoute: typeof SettingsRoute
  TasksRoute: typeof TasksRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies': {
      id: '/companies'
      path: '/companies'
      fullPath: '/companies'
      preLoaderRoute: typeof CompaniesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts': {
      id: '/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof ContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipeline': {
      id: '/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof PipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies/': {
      id: '/companies/'
      path: '/'
      fullPath: '/companies/'
      preLoaderRoute: typeof CompaniesIndexRouteImport
      parentRoute: typeof CompaniesRoute
    }
    '/companies/$contactId': {
      id: '/companies/$contactId'
      path: '/$contactId'
      fullPath: '/companies/$contactId'
      preLoaderRoute: typeof CompaniesContactIdRouteImport
      parentRoute: typeof CompaniesRoute
    }
    '/companies/org/$companyId': {
      id: '/companies/org/$companyId'
      path: '/org/$companyId'
      fullPath: '/companies/org/$companyId'
      preLoaderRoute: typeof CompaniesOrgCompanyIdRouteImport
      parentRoute: typeof CompaniesRoute
    }
  }
}

interface CompaniesRouteChildren {
  CompaniesContactIdRoute: typeof CompaniesContactIdRoute
  CompaniesIndexRoute: typeof CompaniesIndexRoute
  CompaniesOrgCompanyIdRoute: typeof CompaniesOrgCompanyIdRoute
}

const CompaniesRouteChildren: CompaniesRouteChildren = {
  CompaniesContactIdRoute: CompaniesContactIdRoute,
  CompaniesIndexRoute: CompaniesIndexRoute,
  CompaniesOrgCompanyIdRoute: CompaniesOrgCompanyIdRoute,
}

const CompaniesRouteWithChildren = CompaniesRoute._addFileChildren(
  CompaniesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompaniesRoute: CompaniesRouteWithChildren,
  ContactsRoute: ContactsRoute,
  PipelineRoute: PipelineRoute,
  SettingsRoute: SettingsRoute,
  TasksRoute: TasksRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
